### ISSUE TITLE
Gradle : Create a zip file to be able to deploy

### ISSUE THREAD

**Issue by vdemeester** [vdemeester/idea-docker#17]
Create a zip file to make the plugin deployable on a Intellij installation. Define a releaseForIdea task.

**Comment by FaustXVI** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=9194175)](https://www.bountysource.com/issues/9194175-gradle-create-a-zip-file-to-be-able-to-deploy?utm_source=9194175&utm_medium=shield&utm_campaign=ISSUE_BADGE)
